services:
  api:
    image: musapi
    build: .
    ports:
      - "8088:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_PASSWORD=Musapi_2025
    depends_on:
      - db
    networks:
      - api-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Musapi_2025
      - ACCEPT_EULA=Y
    ports:
      - "14330:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - api-network

  dbinit:  # <----- aquí, al mismo nivel que api y db, y dentro de services:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    entrypoint: >
      bash -c "
        sleep 30 &&
        /opt/mssql-tools/bin/sqlcmd -S db -U SA -P 'Musapi_2025' -i /sqlscript.sql
      "
    volumes:
      - ./sql/sqlscript.sql:/sqlscript.sql
    networks:
      - api-network
    restart: "no"
    # Este servicio se apaga después de ejecutar el script

networks:
  api-network:
    driver: bridge

volumes:
  sql-data: